export const translations = {
  "zh-CN": {
    // 侧边栏
    newChat: "新对话",
    cryptoDataHub: "加密数据中心",
    preTgeReport: "Pre-tge 报告",
    appearance: "外观",
    language: "语言",
    learnAboutSurf: "了解 Surf",

    // 主题
    themeSystem: "跟随系统",
    themeLight: "浅色",
    themeDark: "深色",

    // 主页
    mainTitle: "今天我们在加密世界探索什么？",
    productHunt: "Product Hunt",
    productOfDay: "#1 每日产品",
    searchPlaceholder: "用你的加密好奇心挑战 Surf AI",

    // 搜索按钮
    ask: "提问",
    research: "研究",
    executor: "执行器",
    beta: "测试版",

    // 热门问题
    hottestQuestion: "热门问题",

    // Agent Tools
    agentToolsTitle: "查看 Surf 为更智能的加密洞察量身定制的代理工具",
    socialSentiment: "社交情绪分析",
    socialSentimentDesc: "实时跟踪 100,000+ 精选加密 KOL，分析情绪和关键观点。",
    technicalAnalysis: "技术分析",
    technicalAnalysisDesc: "利用 200+ 技术指标和衍生品市场数据，提供精确的趋势和信号，实时交易洞察。",
    onchainTracker: "链上追踪器",
    onchainTrackerDesc: "跟踪钱包行为、代币流动和链上活动，覆盖 40+ 兼容区块链网络。",
    deepSearch: "深度搜索代理",
    deepSearchDesc: "每次查询果断扫描 200+ 网页，利用我们专有的 Surf 数据库捕捉实时趋势信号。",

    // 报告功能
    reportsTitle: "Surf AI 生成的顶级加密项目报告",
    professionalLayout: "专业布局",
    professionalLayoutDesc: "简洁、可发布的格式，旨在实现最大的清晰度和影响力。",
    nerHighlighting: "NER 高亮",
    nerHighlightingDesc: "使用先进的命名实体识别 (NER) 自动突出显示关键实体。",
    interactiveCharts: "交互式图表",
    interactiveChartsDesc: "动态、可点击的图表，让您可以实时探索数据洞察。",

    // 登录
    login: "登录",

    // 钱包
    connectWallet: "连接钱包",
    walletAddress: "钱包地址",
    balance: "余额",
    changeNetwork: "切换网络",
    disconnect: "断开连接",
  },
  en: {
    // Sidebar
    newChat: "New Chat",
    cryptoDataHub: "Crypto Data Hub",
    preTgeReport: "Pre-tge Report",
    appearance: "Appearance",
    language: "Language",
    learnAboutSurf: "Learn About Surf",

    // Theme
    themeSystem: "System",
    themeLight: "Light",
    themeDark: "Dark",

    // Main
    mainTitle: "What are we exploring in crypto today?",
    productHunt: "Product Hunt",
    productOfDay: "#1 Product of the Day",
    searchPlaceholder: "Challenge Surf AI with your crypto curiosity",

    // Search buttons
    ask: "Ask",
    research: "Research",
    executor: "Executor",
    beta: "Beta",

    // Hot questions
    hottestQuestion: "Hottest Question",

    // Agent Tools
    agentToolsTitle: "Check out Surf's tailored agent tools for smarter crypto insights",
    socialSentiment: "Social Sentiment Analysis",
    socialSentimentDesc: "Real-time tracking of 100,000+ curated crypto KOLs, analyzing sentiment and key opinions.",
    technicalAnalysis: "Technical Analysis",
    technicalAnalysisDesc: "Leverages 200+ technical indicators and derivatives market data to deliver precise trends and signals for real-time trading insights.",
    onchainTracker: "Onchain Tracker",
    onchainTrackerDesc: "Track wallet behaviors, token flows, and onchain activity across 40+ compatible blockchain networks.",
    deepSearch: "Deep Search Agent",
    deepSearchDesc: "Every query decisively scans over 200+ web pages and leverages our proprietary Surf database to capture live trend signals.",

    // Reports
    reportsTitle: "Top-tier crypto project reports generated by Surf AI",
    professionalLayout: "Professional layout",
    professionalLayoutDesc: "A sleek, publication-ready format designed for maximum clarity and impact.",
    nerHighlighting: "NER highlighting",
    nerHighlightingDesc: "Automatically highlight key entities using advanced Named Entity Recognition (NER).",
    interactiveCharts: "Interactive charts",
    interactiveChartsDesc: "Dynamic, clickable charts that can make you explore data insights in real-time.",

    // Login
    login: "Login",

    // Wallet
    connectWallet: "Connect Wallet",
    walletAddress: "Wallet Address",
    balance: "Balance",
    changeNetwork: "Change Network",
    disconnect: "Disconnect",
  },
  ja: {
    // サイドバー
    newChat: "新しいチャット",
    cryptoDataHub: "暗号データハブ",
    preTgeReport: "Pre-tge レポート",
    appearance: "外観",
    language: "言語",
    learnAboutSurf: "Surf について",

    // テーマ
    themeSystem: "システム",
    themeLight: "ライト",
    themeDark: "ダーク",

    // メイン
    mainTitle: "今日は暗号で何を探索していますか？",
    productHunt: "Product Hunt",
    productOfDay: "#1 今日の製品",
    searchPlaceholder: "暗号の好奇心で Surf AI に挑戦",

    // 検索ボタン
    ask: "質問",
    research: "リサーチ",
    executor: "エグゼキューター",
    beta: "ベータ版",

    // ホットな質問
    hottestQuestion: "ホットな質問",

    // Agent Tools
    agentToolsTitle: "よりスマートな暗号インサイトのための Surf のカスタマイズされたエージェントツールをご覧ください",
    socialSentiment: "ソーシャルセンチメント分析",
    socialSentimentDesc: "100,000以上の厳選された暗号KOLをリアルタイムで追跡し、センチメントと主要な意見を分析します。",
    technicalAnalysis: "テクニカル分析",
    technicalAnalysisDesc: "200以上のテクニカル指標とデリバティブ市場データを活用して、リアルタイム取引インサイトのための正確なトレンドとシグナルを提供します。",
    onchainTracker: "オンチェーントラッカー",
    onchainTrackerDesc: "40以上の互換性のあるブロックチェーンネットワークで、ウォレットの動作、トークンフロー、オンチェーンアクティビティを追跡します。",
    deepSearch: "ディープサーチエージェント",
    deepSearchDesc: "すべてのクエリは200以上のWebページを決定的にスキャンし、独自のSurfデータベースを活用してライブトレンド信号をキャプチャします。",

    // レポート
    reportsTitle: "Surf AIによって生成されたトップティアの暗号プロジェクトレポート",
    professionalLayout: "プロフェッショナルレイアウト",
    professionalLayoutDesc: "最大の明瞭さと影響力のために設計された洗練された出版準備完了形式。",
    nerHighlighting: "NERハイライト",
    nerHighlightingDesc: "高度な固有表現認識（NER）を使用して主要エンティティを自動的にハイライト表示します。",
    interactiveCharts: "インタラクティブチャート",
    interactiveChartsDesc: "リアルタイムでデータインサイトを探索できる動的でクリック可能なチャート。",

    // ログイン
    login: "ログイン",

    // ウォレット
    connectWallet: "ウォレット接続",
    walletAddress: "ウォレットアドレス",
    balance: "残高",
    changeNetwork: "ネットワーク変更",
    disconnect: "接続解除",
  },
  ko: {
    // 사이드바
    newChat: "새 채팅",
    cryptoDataHub: "암호화 데이터 허브",
    preTgeReport: "Pre-tge 리포트",
    appearance: "외관",
    language: "언어",
    learnAboutSurf: "Surf 알아보기",

    // 테마
    themeSystem: "시스템",
    themeLight: "라이트",
    themeDark: "다크",

    // 메인
    mainTitle: "오늘 암호화폐에서 무엇을 탐험하고 있나요?",
    productHunt: "Product Hunt",
    productOfDay: "#1 오늘의 제품",
    searchPlaceholder: "암호화폐 호기심으로 Surf AI에 도전하세요",

    // 검색 버튼
    ask: "질문",
    research: "리서치",
    executor: "실행기",
    beta: "베타",

    // 핫한 질문
    hottestQuestion: "가장 핫한 질문",

    // Agent Tools
    agentToolsTitle: "더 스마트한 암호화폐 인사이트를 위한 Surf의 맞춤형 에이전트 도구를 확인하세요",
    socialSentiment: "소셜 감정 분석",
    socialSentimentDesc: "100,000명 이상의 엄선된 암호화폐 KOL을 실시간으로 추적하여 감정과 주요 의견을 분석합니다.",
    technicalAnalysis: "기술적 분석",
    technicalAnalysisDesc: "200개 이상의 기술 지표와 파생상품 시장 데이터를 활용하여 실시간 거래 인사이트를 위한 정확한 트렌드와 신호를 제공합니다.",
    onchainTracker: "온체인 트래커",
    onchainTrackerDesc: "40개 이상의 호환 가능한 블록체인 네트워크에서 지갑 동작, 토큰 흐름 및 온체인 활동을 추적합니다.",
    deepSearch: "딥 서치 에이전트",
    deepSearchDesc: "모든 쿼리는 200개 이상의 웹 페이지를 결정적으로 스캔하고 독점 Surf 데이터베이스를 활용하여 실시간 트렌드 신호를 캡처합니다.",

    // 리포트
    reportsTitle: "Surf AI가 생성한 최고 수준의 암호화폐 프로젝트 리포트",
    professionalLayout: "전문적인 레이아웃",
    professionalLayoutDesc: "최대의 명확성과 영향력을 위해 설계된 세련되고 출판 준비가 완료된 형식.",
    nerHighlighting: "NER 하이라이팅",
    nerHighlightingDesc: "고급 개체명 인식(NER)을 사용하여 주요 개체를 자동으로 강조 표시합니다.",
    interactiveCharts: "인터랙티브 차트",
    interactiveChartsDesc: "실시간으로 데이터 인사이트를 탐색할 수 있는 동적이고 클릭 가능한 차트.",

    // 로그인
    login: "로그인",

    // 지갑
    connectWallet: "지갑 연결",
    walletAddress: "지갑 주소",
    balance: "잔액",
    changeNetwork: "네트워크 변경",
    disconnect: "연결 해제",
  },
};

export type TranslationKey = keyof typeof translations["zh-CN"];
